### ISSUE TITLE
cannot load such file -- async/websocket/server/rack

### ISSUE THREAD

**Issue by matti** [socketry/async-websocket#13]
I copy/pasted https://github.com/socketry/async-websocket#server-side-with-rack--falcon

Isn't it 'async/websocket/adapters/rack' ?

**Comment by ioquatix** [comment]
Yeah, it's changed but I'll need to update the documentation. Sorry.

**Comment by Nakilon** [comment]
```none
$ gem list async

*** LOCAL GEMS ***

async (1.30.1)
async-container (0.16.12)
async-http (0.60.1, 0.56.5)
async-http-cache (0.4.3)
async-io (1.32.2)
async-pool (0.3.9)
async-websocket (0.25.1, 0.19.0)
```

**Comment by Nakilon** [comment]
nevermind

1. I had Gemfile in current dir and falcons seems to consume it without `bundle`
2. Another error I faced (undefind `run`) was due to example being copypasted as `temp.rb`, not `temp.ru`

**Comment by ioquatix** [comment]
Thanks for reporting back the issues you faced, I'm sure it can help other people too.
