### ISSUE TITLE
Problem connecting to websocket

### ISSUE THREAD

**Issue by michelboaventura** [socketry/async-websocket#16]
Hi,

I'm trying to connect to a crypto exchange to get some data using the code bellow. If I use the Event Machine version everything works, but if I use the async-websocket (which is commented) I always get a `Protocol::HTTP2::StreamError: Stream closed!`. Could you please help me debug this further?

```Ruby
require 'async'
require 'async/http/endpoint'
require 'async/io/stream'
require 'async/websocket/client'
require 'json'
require 'websocket-eventmachine-client'

payload = {
  OMSId: 1,
  InstrumentId: 1,
  Interval: 60,
  IncludeLastCount: 10
}

frame = {
  m: 0,
  i: 2,
  n: 'SubscribeTicker',
  o: payload.to_json
}.to_json

url = 'wss://api.coinext.com.br/WSGateway'

# Async do |task|
#   endpoint = Async::HTTP::Endpoint.parse(url)
#
#   Async::WebSocket::Client.connect(endpoint) do |connection|
#     connection.write(frame)
#   end
# end

EM.run do
  ws = WebSocket::EventMachine::Client.connect(uri: url)

  ws.onopen do
    ws.send(frame)
  end

  ws.onmessage do |message|
    puts message
  end
end
```

**Comment by ioquatix** [comment]
Does the remote endpoint support HTTP/2 websockets? Maybe we need to detect this situation. The error implies it's trying to connect using HTTP/2 but the websocket connection isn't supported. We probably need to fall back to HTTP/1 in this case.

**Comment by ioquatix** [comment]
You can force it to use HTTP/1... something like:

```
endpoint = Async::HTTP::Endpoint.parse("https://remote-server.com", alpn_protocols: Async::HTTP::Protocol::HTTP11.names)

Async::WebSocket::Client.connect(endpoint) do ...
```

Can you try that and report back? Try enabling verbose logging

```
CONSOLE_LOG_LEVEL=debug my-command
```

or 

```
require 'async/logger'
Async.logger.debug!
```

**Comment by michelboaventura** [comment]
I've tried forcing HTTP/1 and it worked, so it seems like the remote endpoint doesn't support HTTP/2. Thank you for the help!

**Comment by ioquatix** [comment]
It supports http/2 just not http/2 websockets. It’s hard to auto detect this so it should be fine to use http/1 we sockets by default in your case.

**Comment by ioquatix** [comment]
If you have time can you submit a PR to show under Usage in the README how to do this and why?
