### ISSUE TITLE
Any way to connect via a proxy?

### ISSUE THREAD

**Issue by zgalili** [socketry/async-websocket#17]
Hi :)

In our production environment we need to connect trough a proxy,
is there any way to do it with async-websocket?

Thanks,
Ziv.

**Comment by ioquatix** [comment]
Yes, it's possible.

You need to create an HTTP client connected to your proxy with the appropriate authentication.

Then you need to create a proxied endpoint, e.g. https://github.com/socketry/async-http/blob/master/spec/async/http/proxy_spec.rb#L33-L36

Then you need to use async web socket to connect via this proxied endpoint.

If you are using this in a commercial project, please consider sponsoring this project. Higher levels of sponsorship will allow me to dedicate time to your specific problems, including the eco-system for everyone!

**Comment by ioquatix** [comment]
Another company sponsored the proxy implementation. It's part of async-http.
