### ISSUE TITLE
Integration with Stimulus Reflex ?

### ISSUE THREAD

**Issue by nic-lan** [socketry/async-websocket#28]
Hi, 

very cool project.

I noticed that a rails adapter has been recently added and that it has been used in one of the examples provided in the `live` gem.

Since `live` gem readme is linking `stimulus-reflex`, i would like to know if there is any plan and/or interest to somehow allow integration of `async-websocket` with it ( as a `cable-ready` alternative for example ) or the idea here is more likely to extend `live` gem to be a full alternative to stimulus-reflex.

Thank you.

**Comment by ioquatix** [comment]
I think there are some plans to do this but it's not something I'm personally planning to implement right now. The way I see it, provided SR is not depending on ActionCable as a bridge, it should be totally feasible to use SR in the same way - i.e.

- Incoming request to Rails controller.
- Create WebSocket connection.
- Create Stimulus Reflex "instance" and possibly adaptor for WebSocket connection.
- Bind them together and run them.

However if SR is depending on the ActionCable interface, it may become more tricky. I don't know the details.

**Comment by ioquatix** [comment]
Regarding `live` becoming an alternative to SR. I'm not sure what you mean by "full". Basically, `live` is, for what it's worth, feature complete. We will certainly continue to develop it, but from my point of view, but I think the problem space is fairly well understood and it's more a matter of reducing friction than designing new abstractions.

**Comment by nic-lan** [comment]
I understand.  
thank you. 

> I'm not sure what you mean by "full". 

it was not exactly the best phrasing. apologies for that.
