### ISSUE TITLE
Connect client with headers

### ISSUE THREAD

**Issue by bryanp** [socketry/async-websocket#3]
The [client example](https://github.com/socketry/async-websocket/blob/9646f8cfcfa44f828c4e18a47c6bb1d5455ef560/examples/chat/client.rb) works great, but hitting a situation where I need to connect with headers. Having trouble understanding if this is currently supported, and my attempts to do this through `Async::HTTP::URLEndpoint` or the client connection itself haven't panned out.

**Comment by ioquatix** [comment]
It took a quick look, and the underlying websocket driver doesn't expose setting custom headers.

It seems like a missing feature.

There are two options:

1. Add headers to https://github.com/faye/websocket-driver-ruby/blob/ee39af83d03ae3059c775583e4c4b291641257b8/lib/websocket/driver.rb#L82 probably via an option (e.g. `headers:`)
2. Fork/rewrite the underlying driver code and use `async-http` which allows you to specify headers, work over http/2 (if that's ever standardised), etc.

Honestly, option 1 is a lot more bang for the buck, but option 2 is probably the longer term solution for this library.

**Comment by ioquatix** [comment]
Actually my bad, it just occurred to me there might be a method to set headers and there it is: https://github.com/faye/websocket-driver-ruby/blob/ee39af83d03ae3059c775583e4c4b291641257b8/lib/websocket/driver.rb#L96

We already expose `client.driver` so it should be as simple as calling `client.driver.set_header` at the appropriate place... or adding it a a constructor.

**Comment by bryanp** [comment]
Got it. Since `Async::WebSocket::Connection` calls `driver.start` in `initialize`, would have to do:

```ruby
module Async
  module WebSocket
    class Client < Async::WebSocket::Connection
      def initialize(socket, url = "ws://.", headers = {})
        @url = url

        super socket, build_client(headers)
      end

      private

      def build_client(headers)
        ::WebSocket::Driver.client(self).tap do |client|
          headers.each do |key, value|
            client.set_header(key, value)
          end
        end
      end
    end
  end
end
```

I confirmed this worked for my use-case. If you're interested in supporting in the library, I'll open a PR.

**Comment by ioquatix** [comment]
Yes please make pr:)
