### ISSUE TITLE
0.22.0: zlib(finalizer): the stream was freed prematurely

### ISSUE THREAD

**Issue by zhulik** [socketry/async-websocket#42]
Hello,

after updating to 0.22.0 from 0.19.2 and making adjustments for the new read/write interface I started getting warnings from zlib:
```
zlib(finalizer): the stream was freed prematurely.
```

Besides that my code works as expected.

I couldn't precisely trace what exactly causes printing of this warning, do you have any ideas where I can start from?

Thanks!

**Comment by zhulik** [comment]
Some updates: warning is only shown with ruby 2.7 and 3.0, 3.1 is not affected.

**Comment by ioquatix** [comment]
Yeah I removed that message from the CRuby native extension for zlib. Thanks for confirming the fix!
