### ISSUE TITLE
Testing async-websocket in process 

### ISSUE THREAD

**Issue by jch** [socketry/async-websocket#74]
I saw there was a rack adapter and was curious if there was something like rack-test or an extension to support testing within the same process as the running test.

If there isn't, would the best starting point be looking at the existing sus http fixtures and how it sets up a server there?

**Comment by ioquatix** [comment]
What kind of thing do you want to test? If it's HTTP then `sus-fixtures-async-http` is a good place to start.

**Comment by jch** [comment]
Ya I saw that. Will wrap my head around how ServerContext#before makes that server and collect the messages for assertions. Appreciate it.
