### ISSUE TITLE
Unable to send authorization headers

### ISSUE THREAD

**Issue by adenta** [socketry/async-websocket#75]
Couldn't find documentation either.

``` 
OPENAI_URL = 'wss://api.openai.com/v1/realtime?model=gpt-4o-realtime-preview-2024-10-01'
    OPENAI_HEADERS = {
      'Authorization' => "Bearer #{ENV['OPENAI_API_KEY']}",
      'OpenAI-Beta' => 'realtime=v1'
    }
    Async do
      openai_endpoint = Async::HTTP::Endpoint.parse(OPENAI_URL)
      openai_connection = Async::WebSocket::Client.connect(openai_endpoint, headers: OPENAI_HEADERS)
    end
```

gives me a `Failed to negotiate connection!` when a similar turn of phrase works with websocket-client-simple. I am fairly certain I am not passing in the headers properly, and I couldnt find any documentation about what exactly this library is looking for.

**Comment by ioquatix** [comment]
This looks like a missing feature.

**Comment by michelson** [comment]
Hi, I'm able to do it with async. example:


```ruby
def ws_client
    require "async"
    require "async/http"
    require "async/websocket"

    url = "wss://api.openai.com/v1/realtime?model=gpt-4o-realtime-preview-2024-10-01"

    # Creating headers for the request
    headers = {
      "Authorization" => "Bearer #{ENV.fetch('OPENAI_API_KEY', nil)}",
      "OpenAI-Beta" => "realtime=v1"
    }

    Async do |task|
      endpoint = Async::HTTP::Endpoint.parse(url, alpn_protocols: Async::HTTP::Protocol::HTTP11.names)

      Async::WebSocket::Client.connect(endpoint, headers: headers) do |connection|
        input_task = task.async do
          while line = $stdin.gets

            text = {
              type: "response.create",
              response: {
                modalities: ["text"],
                instructions: "Please assist the user."
              }
            }
            message = Protocol::WebSocket::TextMessage.generate(text) # ({ text: line })
            message.send(connection)
            connection.flush
          end
        end

        puts "Connected..."
        while message = connection.read
          puts "> #{message.to_h}"
        end
      ensure
        input_task&.stop
      end
    end
  end
  ```

**Comment by adenta** [comment]
Are you seeing `session.created` events from the server? Would the above example work with function calling?

I was able to get a basic example working, but it _would not_ call defined tools/functions

**Comment by adenta** [comment]
looks like this is the async-websocket repo, not the ruby-openai, so closing

**Comment by ioquatix** [comment]
Okay, just to confirm, this is now working for you, at least the websocket part?

**Comment by adenta** [comment]
It’s working for the other guy, I haven’t tested it yet. I went with Faye

**Comment by adenta** [comment]
Working, ` Async::HTTP::Protocol::HTTP11.names` did the trick. Seems like HTTP2 is like, half supported (some things work, some dont. using the HTTP11.names got function calling working properly)

**Comment by ioquatix** [comment]
Just to clarify, do you mean `wss://api.openai.com`, when using HTTP/2 WebSockets, does not work as documented, or the same as when using HTTP/1 WebSockets? Do you mind posting a snippet of your code for other users who might stumble on this issue?

**Comment by adenta** [comment]
Planning to publish once I have something finished to share
